### ISSUE TITLE
IllegalStateException: [GET http://www.rehttp.net/i?u] failed in 1ms: no protocol: 

### ISSUE THREAD

**Issue by yegor256** [yegor256/rehttp#10]
https://sentry.io/zerocracy/rehttp/issues/333351118/

```
MalformedURLException: no protocol: 
    at java.net.URL.<init>(URL.java:593)
    at java.net.URL.<init>(URL.java:490)
    at java.net.URL.<init>(URL.java:439)
    at net.rehttp.tk.TkInfo.act(TkInfo.java:66)
    at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:154)
...
(27 additional frame(s) were not displayed)

IllegalStateException: [GET http://www.rehttp.net/i?u] failed in 1ms: no protocol: 
    at org.takes.facets.fallback.TkFallback.error(TkFallback.java:233)
    at org.takes.facets.fallback.TkFallback.route(TkFallback.java:112)
    at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:54)
    at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:66)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
...
(17 additional frame(s) were not displayed)

[GET http://www.rehttp.net/i?u] failed in 1ms: no protocol: 
```

**Comment by 0crat** [comment]
I'm not managing ` yegor256/rehttp ` GitHub repository. You have to contact me in Slack first. Our [policy](http://datum.zerocracy.com/pages/policy.html) explains how.

**Comment by yegor256** [comment]
should work now, in the latest version

**Comment by 0crat** [comment]
Job `gh:yegor256/rehttp#10` is not assigned, can't get performer
