### ISSUE TITLE
IllegalStateException: [GET http://p.rehttp.net/] failed in 2ms: no protocol: 

### ISSUE THREAD

**Issue by yegor256** [yegor256/rehttp#16]
https://sentry.io/zerocracy/rehttp/issues/422711069/

```
MalformedURLException: no protocol: 
    at java.net.URL.<init>(URL.java:593)
    at java.net.URL.<init>(URL.java:490)
    at java.net.URL.<init>(URL.java:439)
    at net.rehttp.tk.TkApp.lambda$app$0(TkApp.java:93)
    at org.takes.facets.fork.FkHost$1.route(FkHost.java:81)
...
(28 additional frame(s) were not displayed)

IllegalStateException: [GET http://p.rehttp.net/] failed in 2ms: no protocol: 
    at org.takes.facets.fallback.TkFallback.error(TkFallback.java:233)
    at org.takes.facets.fallback.TkFallback.route(TkFallback.java:112)
    at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:54)
    at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:66)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
...
(18 additional frame(s) were not displayed)

[GET http://p.rehttp.net/] failed in 2ms: no protocol: 
```

**Comment by yegor256** [comment]
should be OK in the latest version

**Comment by 0crat** [comment]
Job `gh:yegor256/rehttp#16` is not assigned, can't get performer
