### ISSUE TITLE
throwing error when I forget one /

### ISSUE THREAD

**Issue by ZiyaVakhobov** [yegor256/rehttp#22]
Here is example. 
https://www.rehttp.net/p/https:/www.uz

throws this error; 
java.lang.RuntimeException: java.lang.IllegalArgumentException: protocol = https host = null
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1506)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3036)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:489)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
	at com.jcabi.http.request.JdkRequest$1.send(JdkRequest.java:121)
	at com.jcabi.http.request.BaseRequest.fetchResponse(BaseRequest.java:355)
	at com.jcabi.http.request.BaseRequest.fetch(BaseRequest.java:270)
	at org.takes.tk.TkProxy.act(TkProxy.java:121)
	at net.rehttp.base.DyTake.act(DyTake.java:100)
	at net.rehttp.tk.TkApp.lambda$app$1(TkApp.java:100)
	at org.takes.facets.fork.FkRegex.route(FkRegex.java:210)
	at org.takes.facets.fork.FkChain.route(FkChain.java:75)
	at org.takes.facets.fork.TkFork.act(TkFork.java:100)
	at org.takes.tk.TkMeasured$1.act(TkMeasured.java:67)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkVersioned$1.act(TkVersioned.java:73)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:71)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.http.BkBasic.print(BkBasic.java:108)
	at org.takes.http.BkBasic.accept(BkBasic.java:84)
	at org.takes.http.BkSafe$1.accept(BkSafe.java:51)
	at org.takes.http.BkWrap.accept(BkWrap.java:52)
	at org.takes.http.BkTimeable.accept(BkTimeable.java:89)
	at org.takes.http.BkParallel$1$1.run(BkParallel.java:89)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: protocol = https host = null
	at sun.net.spi.DefaultProxySelector.select(DefaultProxySelector.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1150)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	... 26 more

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@ziyavakhobov[/z](https://www.0crat.com/u/ziyavakhobov) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3RFVLU72) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job [#22](https://github.com/yegor256/rehttp/issues/22) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Thanks for your contribution, @ziyavakhobov[/z](https://www.0crat.com/u/ziyavakhobov)! If you would be a member of [the project](https://www.0crat.com/p/C3RFVLU72), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#22](https://github.com/yegor256/rehttp/issues/22); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#22](https://github.com/yegor256/rehttp/issues/22); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#22](https://github.com/yegor256/rehttp/issues/22); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#22](https://github.com/yegor256/rehttp/issues/22); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#22](https://github.com/yegor256/rehttp/issues/22); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#22](https://github.com/yegor256/rehttp/issues/22); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#22](https://github.com/yegor256/rehttp/issues/22); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by dgarus** [comment]
@g4s8, hello!

Could you help me?
My PR was merged, what should I do to get the issue closed?

**Comment by g4s8** [comment]
@dgarus hi, you need to check https://www.zerocracy.com/policy.html#7 (DOD: https://www.yegor256.com/2014/04/15/definition-of-done.html)

**Comment by dgarus** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/rehttp/issues/22#issuecomment-538380679))

@dgarus This is what I know about this job in [C3RFVLU72](https://www.0crat.com/p/C3RFVLU72), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#22](https://github.com/yegor256/rehttp/issues/22) is [in scope](http://www.zerocracy.com/policy.html#14) for 3mon
  * The role is `DEV`
  * The job is not assigned to anyone
  * The [budget](http://www.zerocracy.com/policy.html#4) is not set yet
  * These users are banned and won't be assigned:
    * @ziyavakhobov[/z](https://www.0crat.com/u/ziyavakhobov): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3RFVLU72?q=%7Bjob%3A%27gh%3Ayegor256%2Frehttp%2322%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by dgarus** [comment]
@ZiyaVakhobov, hello!

The fix was merged, could you close the issue?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#22](https://github.com/yegor256/rehttp/issues/22); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@ZiyaVakhobov @dgarus I'm closing

**Comment by 0crat** [comment]
Job `gh:yegor256/rehttp#22` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#22](https://github.com/yegor256/rehttp/issues/22) is now out of scope
