### ISSUE TITLE
http://www.rehttp.net/ crashed after clicking on "Open" button.

### ISSUE THREAD

**Issue by andriisoldatenko** [yegor256/rehttp#9]
1. Go http://www.rehttp.net/
2. Click "Open"
3. You see Java exception 
```
java.lang.IllegalStateException: [GET http://www.rehttp.net/i?u] failed in 0ms: no protocol: 
	at org.takes.facets.fallback.TkFallback.error(TkFallback.java:233)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:112)
	at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:54)
	at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:66)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.flash.TkFlash.act(TkFlash.java:108)
	at org.takes.tk.TkMeasured$1.act(TkMeasured.java:67)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkVersioned$1.act(TkVersioned.java:72)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:71)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.http.BkBasic.print(BkBasic.java:108)
	at org.takes.http.BkBasic.accept(BkBasic.java:84)
	at org.takes.http.BkSafe$1.accept(BkSafe.java:51)
	at org.takes.http.BkWrap.accept(BkWrap.java:52)
	at org.takes.http.BkTimeable.accept(BkTimeable.java:89)
	at org.takes.http.BkParallel$1$1.run(BkParallel.java:89)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.MalformedURLException: no protocol: 
	at java.net.URL.(URL.java:593)
	at java.net.URL.(URL.java:490)
	at java.net.URL.(URL.java:439)
	at net.rehttp.tk.TkInfo.act(TkInfo.java:66)
	at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:154)
	at org.takes.facets.fork.FkRegex.route(FkRegex.java:209)
	at org.takes.facets.fork.FkChain.route(FkChain.java:75)
	at org.takes.facets.fork.TkFork.act(TkFork.java:100)
	at org.takes.tk.TkGzip$1.act(TkGzip.java:58)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.forward.TkForward.act(TkForward.java:68)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:85)
	... 20 more
```

**Comment by 0crat** [comment]
@andriisoldatenko I'm not managing this repo, remove the [webhook](https://github.com/yegor256/rehttp/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by gersimuca** [comment]
You are not handling the error when we have a empty submission, you can hotfix to make the field required to be filled.
After you can implement some error handling and remove the hotfix.

**Comment by yegor256** [comment]
@gersimuca you are welcome to submit a pull request!
